### ISSUE TITLE
[ENH]: Allow configuration of environment variables

### ISSUE THREAD

**Issue by mrsimonemms** [pmoscode-helm/gotify#16]
### Description

Thanks for this chart, it works well. I'd like to move the `GOTIFY_DEFAULTUSER_NAME` and `GOTIFY_DEFAULTUSER_PASS` into a secret.

My suggestion is to wrap these in an `if` statement and then have an `additionalEnvVars` array of objects that can be used. This then would have something like this in the configuration:

```yaml
additionalEnvVars:
  - name: GOTIFY_DEFAULTUSER_NAME
    valueFrom:
      secretKeyRef:
        name: some-secret
        key: username
  - name: GOTIFY_DEFAULTUSER_PASS
    valueFrom:
      secretKeyRef:
        name: some-secret
        key: password
```

### Additional Information

Will raise a PR for this
